# Generated by Django 5.0 on 2023-12-15 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='id',
        ),
        migrations.RemoveField(
            model_name='model_file',
            name='model_id',
        ),
        migrations.AddField(
            model_name='model',
            name='model_id',
            field=models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='model_file',
            name='model_file_model_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model_file_model_id', to='fl_client.model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_version',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Local_Project',
            fields=[
                ('local_project_id', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('local_project_title', models.CharField(max_length=250)),
                ('local_project_description', models.TextField()),
                ('local_project_type', models.CharField(choices=[('LC', 'Local Project'), ('RM', 'Remote Project'), ('FD', 'Federated Project')], default='LC', max_length=2)),
                ('local_project_creation_date', models.DateTimeField(auto_now_add=True)),
                ('local_project_updated_date', models.DateTimeField(auto_now=True)),
                ('local_project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_project_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_doc_title', models.CharField(max_length=250)),
                ('model_doc_filename', models.CharField(max_length=250)),
                ('model_doc_creation_date', models.DateTimeField(auto_now_add=True)),
                ('model_doc_updated_date', models.DateTimeField(auto_now=True)),
                ('model_doc_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_doc_model_id', to='fl_client.model')),
                ('model_doc_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_doc_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('queue_state', models.CharField(choices=[('CL', 'Cancelled'), ('CP', 'Completed'), ('CR', 'Created'), ('ER', 'Error'), ('IP', 'In progress'), ('PN', 'Pending'), ('RL', 'Rejected'), ('RS', 'Restarted'), ('ST', 'Started'), ('SP', 'Stopped'), ('UP', 'Updated')], default='CR', max_length=2)),
                ('queue_creation_date', models.DateTimeField(auto_now_add=True)),
                ('queue_updated_date', models.DateTimeField(auto_now=True)),
                ('queue_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_model_id', to='fl_client.model')),
                ('queue_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queue_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
