# Generated by Django 5.0 on 2023-12-14 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Local_Project',
            fields=[
                ('local_project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_project_title', models.CharField(max_length=250)),
                ('local_project_description', models.TextField()),
                ('local_project_creation_date', models.DateTimeField(auto_now_add=True)),
                ('local_project_updated_date', models.DateTimeField(auto_now=True)),
                ('local_project_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='local_project_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
