# Generated by Django 5.0 on 2023-12-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0002_alter_model_model_owner_local_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_project',
            name='local_project_type',
            field=models.CharField(choices=[('LC', 'Local Project'), ('RM', 'Remote Project'), ('FD', 'Federated Project')], default='LC', max_length=2),
        ),
    ]
