# Generated by Django 5.0 on 2023-12-15 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0002_remove_model_id_remove_model_file_model_id_and_more"), ]

    operations = [
        migrations.RemoveField(
            model_name="model_document",
            name="model_doc_owner",
        ),
    ]
