# Generated by Django 5.0 on 2023-12-14 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0003_local_project_local_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='id',
        ),
        migrations.RemoveField(
            model_name='model_file',
            name='model_id',
        ),
        migrations.AddField(
            model_name='model',
            name='model_id',
            field=models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='model_file',
            name='model_file_model_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model_file_model_id', to='fl_client.model'),
        ),
        migrations.AlterField(
            model_name='local_project',
            name='local_project_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='local_project',
            name='local_project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='model_family',
            name='model_family_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ModelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_doc_title', models.CharField(max_length=250)),
                ('model_doc_filename', models.CharField(max_length=250)),
                ('model_doc_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_doc_model_id', to='fl_client.model')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('queue_state', models.CharField(choices=[('CL', 'Cancelled'), ('CP', 'Completed'), ('CR', 'Created'), ('ER', 'Error'), ('IP', 'In progress'), ('PN', 'Pending'), ('RL', 'Rejected'), ('RS', 'Restarted'), ('ST', 'Started'), ('SP', 'Stopped'), ('UP', 'Updated')], default='CR', max_length=2)),
                ('queue_creation_date', models.DateTimeField(auto_now_add=True)),
                ('queue_updated_date', models.DateTimeField(auto_now=True)),
                ('queue_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_model_id', to='fl_client.model')),
            ],
        ),
    ]
