# Generated by Django 5.0 on 2023-12-15 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0003_remove_model_document_model_doc_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='model_document',
            name='model_doc_owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='model_doc_owner',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
