# Generated by Django 5.0 on 2023-12-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0007_rename_modeldocument_model_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_model_id',
            field=models.BigAutoField(
                editable=False,
                primary_key=True,
                serialize=False),
        ),
    ]
