# Generated by Django 5.0 on 2023-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0018_remove_model_file_model_file_splitted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='model_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
