# Generated by Django 5.0 on 2023-12-24 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0022_document_document_uuid_alter_queue_queue_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="queue",
            name="queue_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
