# Generated by Django 5.0 on 2023-12-24 00:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0024_model_document_modeldoc_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_document",
            name="modeldoc_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True),
        ),
    ]
