# Generated by Django 5.0 on 2023-12-24 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0026_model_model_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="model_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
