# Generated by Django 5.0 on 2023-12-24 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0028_model_file_model_file_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='model_file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
