# Generated by Django 5.0 on 2023-12-24 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0030_model_family_model_family_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_family',
            name='model_family_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
