# Generated by Django 5.0 on 2023-12-24 01:01

import uuid
from django.db import migrations, models


def create_uuid(apps, schema_editor):
    Local_Project = apps.get_model('fl_client', 'Local_Project')
    for local_project in Local_Project.objects.all():
        local_project.local_project_uuid = uuid.uuid4()
        local_project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0031_alter_model_family_model_family_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_project',
            name='local_project_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='local_project',
            name='local_project_uuid',
            field=models.UUIDField(unique=True)
        )
    ]
