# Generated by Django 5.0 on 2023-12-24 01:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0032_local_project_local_project_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local_project",
            name="local_project_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True),
        ),
    ]
