# Generated by Django 5.0 on 2023-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0038_alter_help_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='model_file_filename',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
