# Generated by Django 5.0 on 2023-12-25 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0041_queue_queue_model_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['queue_model_type', 'queue_state']},
        ),
        migrations.AddField(
            model_name='model_document',
            name='modeldoc_creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='model_document',
            name='modeldoc_updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('license_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('license_name', models.CharField(max_length=250)),
                ('license_description', models.TextField(blank=True)),
                ('license_creation_date', models.DateTimeField(auto_now_add=True)),
                ('license_updated_date', models.DateTimeField(auto_now=True)),
                ('license_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='license_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['license_name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('dataset_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dataset_name', models.CharField(max_length=250)),
                ('dataset_description', models.TextField(blank=True)),
                ('dataset_creation_date', models.DateTimeField(auto_now_add=True)),
                ('dataset_updated_date', models.DateTimeField(auto_now=True)),
                ('dataset_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dataset_owner', to=settings.AUTH_USER_MODEL)),
                ('dataset_licence', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dataset_license', to='fl_client.license')),
            ],
        ),
    ]
