# Generated by Django 5.0 on 2023-12-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_client', '0048_alter_dataset_options_alter_license_options_and_more'), ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='help_creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='help',
            name='help_updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
