# Generated by Django 5.0 on 2023-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fl_client",
            "0054_rename_dataset_central_data_datasetcentraldata_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="model_short_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
