# Generated by Django 5.0 on 2023-12-12 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fl_server", "0002_remove_nlp_model_file_nlp_model_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model_file",
            name="model_id",
        ),
        migrations.RemoveField(
            model_name="model_family",
            name="model_family_owner",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Model",
        ),
        migrations.DeleteModel(
            name="Model_File",
        ),
        migrations.DeleteModel(
            name="Model_Family",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
