# Generated by Django 5.0 on 2023-12-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Configuration',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=250)),
                ('agent_description', models.CharField(max_length=250)),
                ('agent_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('agent_port', models.CharField(default='8765', max_length=5)),
                ('agent_state', models.CharField(default='offline', max_length=10)),
            ],
        ),
    ]
