# Generated by Django 5.0 on 2023-12-15 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server', '0007_server_model_agent_configuration_agent_creation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_configuration',
            name='agent_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
