exclude: .*migrations\/.*,.static\/.*,.staticfiles\/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-toml
      - id: check-ast
      - id: debug-statements
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py313-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.30.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "6.0"]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args: [ "--fix", "--config=pyproject.toml" ]
      - id: ruff-format
        args: [ "--config=pyproject.toml" ]
