@startuml
'https://plantuml.com/sequence-diagram

autonumber

"Local Agent" -> "Local Agent": Authentication Request
"Local Agent" --> "Central Server": Autorisation Request
"Central Server" ---> "Local Agent": Autorisation Response
"Local Agent" ---> "Central Server": Training Task Creation
"Local Agent" ---> "Central Server": Model Transfer
"Local Agent" ---> "Central Server": Data Transfer
"Central Server" -> "Central Server": Model Training
"Central Server" -> "Central Server": Task State Update
"Central Server" ---> "Local Agent": Return Trained Model
"Central Server" -> "Central Server": Data Destruction
@enduml