# Copyright (c) 2026 AIMER contributors.
"""
Django settings for AIMER project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from collections.abc import Iterable
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse, urlsplit

from dotenv import load_dotenv

from .template import TEMPLATE_CONFIG as DEFAULT_TEMPLATE_CONFIG
from .template import THEME_LAYOUT_DIR as DEFAULT_THEME_LAYOUT_DIR
from .template import THEME_VARIABLES as DEFAULT_THEME_VARIABLES

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


def env_bool(name: str, *, default: bool = False) -> bool:
    """
    Return a boolean from an environment variable.

    Returns:
        bool: Parsed truth value.

    """
    return os.environ.get(name, str(default)).lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def env_list(name: str, default: Iterable[str] | None = None) -> list[str]:
    """
    Return a list from a comma-separated environment variable.

    Returns:
        list[str]: Trimmed list entries.

    """
    if default is None:
        default = []
    raw_value = os.environ.get(name)
    if raw_value is None:
        return list(default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def env_int(name: str, *, default: int) -> int:
    """Return an integer from an environment variable."""
    raw_value = os.environ.get(name)
    if raw_value is None:
        return default
    try:
        return int(raw_value)
    except ValueError as exc:
        msg = f"{name} must be an integer."
        raise RuntimeError(msg) from exc


def normalize_csrf_origins(origins: Iterable[str]) -> list[str]:
    """
    Normalize CSRF trusted origins to include scheme + host.

    Returns:
        list[str]: Origins with ``scheme://netloc`` only.

    """
    normalized: list[str] = []
    for origin in origins:
        parsed = urlsplit(origin)
        if parsed.scheme and parsed.netloc:
            normalized.append(f"{parsed.scheme}://{parsed.netloc}")
    return normalized


def database_config_from_url(database_url: str) -> dict[str, object]:
    """Build a Django DATABASES entry from a database URL."""
    parsed = urlparse(database_url)
    if parsed.scheme in {"postgres", "postgresql", "postgresql+psycopg"}:
        config: dict[str, object] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
        }
    elif parsed.scheme == "sqlite":
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": unquote(parsed.path.lstrip("/")) or ":memory:",
        }
    else:
        msg = "DATABASE_URL must use postgresql:// or sqlite://."
        raise RuntimeError(msg)

    if parsed.username:
        config["USER"] = unquote(parsed.username)
    if parsed.password:
        config["PASSWORD"] = unquote(parsed.password)
    if parsed.hostname:
        config["HOST"] = parsed.hostname
    if parsed.port:
        config["PORT"] = str(parsed.port)

    options = {
        key: value
        for key, value in parse_qsl(parsed.query, keep_blank_values=False)
        if key
    }
    if options:
        config["OPTIONS"] = options
    return config


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    msg = "SECRET_KEY must be set in the environment."
    raise RuntimeError(msg)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)

ENVIRONMENT = os.environ.get("ENVIRONMENT", "local")
IS_PRODUCTION = ENVIRONMENT.strip().lower() in {"prod", "production"}

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "[::1]"] if DEBUG else [],
)
if IS_PRODUCTION and not ALLOWED_HOSTS:
    msg = "ALLOWED_HOSTS must be set when ENVIRONMENT=production."
    raise RuntimeError(msg)

CSRF_TRUSTED_ORIGINS = normalize_csrf_origins(
    env_list("CSRF_TRUSTED_ORIGINS"),
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_rich",
    "auth.apps.AuthConfig",
    "website.apps.WebsiteConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "AIMER.language_middleware.DefaultLanguageMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auth.middleware.AdminAuditMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AIMER.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "AIMER.context_processors.language_code",
                "AIMER.context_processors.my_setting",
                "AIMER.context_processors.get_cookie",
                "AIMER.context_processors.environment",
            ],
            "libraries": {"theme": "AIMER.template_tags.theme"},
            "builtins": [
                "django.templatetags.static",
                "AIMER.template_tags.theme",
            ],
        },
    },
]

ASGI_APPLICATION = "AIMER.asgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if IS_PRODUCTION and not DATABASE_URL:
    msg = "DATABASE_URL must be set when ENVIRONMENT=production."
    raise RuntimeError(msg)

DATABASES = {
    "default": (
        database_config_from_url(DATABASE_URL)
        if DATABASE_URL
        else {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Default URL on which Django application runs for specific environment
BASE_URL = os.environ.get("BASE_URL", default="http://127.0.0.1:8000")
RAG_SERVICE_URL = os.environ.get("RAG_SERVICE_URL", "").rstrip("/")
RAG_SERVICE_API_KEY = os.environ.get("RAG_SERVICE_API_KEY", "")
RAG_SERVICE_TIMEOUT_SECONDS = float(os.environ.get("RAG_SERVICE_TIMEOUT_SECONDS", "5"))
RAG_RECOMMENDATION_RATE_LIMIT_PER_MINUTE = env_int(
    "RAG_RECOMMENDATION_RATE_LIMIT_PER_MINUTE",
    default=30,
)
EMAIL_VERIFICATION_REQUIRED = env_bool(
    "EMAIL_VERIFICATION_REQUIRED",
    default=IS_PRODUCTION,
)

TEST_RUNNER = "django_rich.test.RichRunner"

# Email
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = env_int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=False)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE_BACKEND = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if IS_PRODUCTION
    else "whitenoise.storage.CompressedStaticFilesStorage"
)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_STORAGE_BACKEND,
    },
}

# Security settings
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if env_bool("SECURE_PROXY_SSL_HEADER_ENABLED", default=IS_PRODUCTION)
    else None
)
SECURE_HSTS_SECONDS = env_int(
    "SECURE_HSTS_SECONDS",
    default=31536000 if IS_PRODUCTION else (3600 if not DEBUG else 0),
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", default=IS_PRODUCTION)
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "aimer.security.audit": {
            "handlers": ["console"],
            "level": os.environ.get("SECURITY_AUDIT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

AUTH_LOGIN_FAILURE_LIMIT = env_int("AUTH_LOGIN_FAILURE_LIMIT", default=5)
AUTH_LOGIN_WINDOW_SECONDS = env_int("AUTH_LOGIN_WINDOW_SECONDS", default=900)
AUTH_LOGIN_LOCKOUT_SECONDS = env_int("AUTH_LOGIN_LOCKOUT_SECONDS", default=900)
EMAIL_VERIFICATION_TOKEN_TTL_HOURS = env_int(
    "EMAIL_VERIFICATION_TOKEN_TTL_HOURS",
    default=24,
)


def validate_production_configuration() -> None:
    """Fail fast on configuration that is unsafe for regulated production."""
    if not IS_PRODUCTION:
        return

    errors: list[str] = []
    parsed_base_url = urlsplit(BASE_URL)

    if DEBUG:
        errors.append("DEBUG must be false.")
    if SECRET_KEY.startswith(("dev-", "test-", "ci-")):
        errors.append("SECRET_KEY must not use a development/test prefix.")
    if len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5:
        errors.append("SECRET_KEY must be at least 50 chars and high entropy.")
    if "*" in ALLOWED_HOSTS:
        errors.append("ALLOWED_HOSTS must not contain '*'.")
    if parsed_base_url.scheme != "https" or parsed_base_url.hostname in {
        "localhost",
        "127.0.0.1",
    }:
        errors.append("BASE_URL must be a public HTTPS URL.")
    if not SECURE_SSL_REDIRECT:
        errors.append("SECURE_SSL_REDIRECT must be enabled.")
    if not SESSION_COOKIE_SECURE:
        errors.append("SESSION_COOKIE_SECURE must be enabled.")
    if not CSRF_COOKIE_SECURE:
        errors.append("CSRF_COOKIE_SECURE must be enabled.")
    if SECURE_HSTS_PRELOAD and SECURE_HSTS_SECONDS < 31536000:
        errors.append("SECURE_HSTS_SECONDS must be at least 31536000 for preload.")
    if EMAIL_VERIFICATION_REQUIRED and not (EMAIL_HOST_USER and EMAIL_HOST_PASSWORD):
        errors.append("Email credentials are required for verified production login.")
    if RAG_SERVICE_URL and not RAG_SERVICE_API_KEY:
        errors.append("RAG_SERVICE_API_KEY is required when RAG_SERVICE_URL is set.")

    if errors:
        joined = " ".join(errors)
        msg = f"Unsafe production configuration: {joined}"
        raise RuntimeError(msg)


# Template Settings
# ------------------------------------------------------------------------------

THEME_LAYOUT_DIR = DEFAULT_THEME_LAYOUT_DIR
TEMPLATE_CONFIG = DEFAULT_TEMPLATE_CONFIG
THEME_VARIABLES = DEFAULT_THEME_VARIABLES

validate_production_configuration()
