@startuml
skinparam linetype ortho

entity "Model_Family" as mf {
  *model_family_id : number <<generated>>
  --
  *name : text
  description : text
}

entity "Model" as m {
  *model_id : number <<generated>>
  --
  *e1_id : number <<FK>>
  other_details : text
}
@enduml