@startuml
'https://plantuml.com/sequence-diagram

autonumber
"Researcher" ---> "Central Server": Authentication Request
"Central Server" ---> "Researcher": Authentication Response
"Researcher" ---> "Central Server": Create project
"Central Server" ---> "Researcher": Autorisation Request
"Researcher" ---> "Central Server": Autorisation Response
"Researcher" ---> "Central Server": Training Task Creation
"Researcher" ---> "Central Server": Model Transfer
"Central Server" ---> "Agent": Model Transfer
"Agent" --> "Agent": Local Training
"Agent" ---> "Central Server": Model trained
"Central Server" --> "Central Server": Aggregation
"Central Server" --> "Researcher": Global Model
@enduml