# Generated by Django 6.0.1 on 2025-02-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="forget_password_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
