# Generated by Django 5.0 on 2023-12-08 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NLP_Model_Family",
            fields=[
                (
                    "model_family_creation_date",
                    models.DateTimeField(auto_created=True),
                ),
                (
                    "model_family_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("model_family_name", models.CharField(max_length=100)),
                (
                    "model_family_updated_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "model_family_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_family_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NLP_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.CharField(max_length=15)),
                ("model_repo", models.CharField(max_length=250)),
                (
                    "model_creation_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("model_updated_date", models.DateTimeField(auto_now=True)),
                (
                    "model_provider",
                    models.CharField(
                        choices=[("HF", "Hugging Face")],
                        default="HF",
                        max_length=2,
                    ),
                ),
                (
                    "model_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family_model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_model_id",
                        to="fl_server.nlp_model_family",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NLP_Model_File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_file_type", models.CharField(max_length=250)),
                ("model_file_filename", models.CharField(max_length=250)),
                (
                    "model_file_extension",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "model_filesize",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "model_file_creation_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "model_file_updated_date",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "NLP_model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="NLP_model_id",
                        to="fl_server.nlp_model",
                    ),
                ),
            ],
        ),
    ]
