# Copyright (c) 2026 AIMER contributors.

"""
Django settings for framework project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse, urlsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


def env_bool(name: str, default: bool = False) -> bool:
    """Parse boolean-like environment variables safely."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    """Parse integer environment variables safely."""
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError as exc:
        msg = f"{name} must be an integer."
        raise RuntimeError(msg) from exc


def database_config_from_url(database_url: str) -> dict[str, object]:
    """Build a Django DATABASES entry from a database URL."""
    parsed = urlparse(database_url)
    if parsed.scheme in {"postgres", "postgresql", "postgresql+psycopg"}:
        config: dict[str, object] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
        }
    elif parsed.scheme == "sqlite":
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": unquote(parsed.path.lstrip("/")) or ":memory:",
        }
    else:
        msg = "DJANGO_DATABASE_URL must use postgresql:// or sqlite://."
        raise RuntimeError(msg)

    if parsed.username:
        config["USER"] = unquote(parsed.username)
    if parsed.password:
        config["PASSWORD"] = unquote(parsed.password)
    if parsed.hostname:
        config["HOST"] = parsed.hostname
    if parsed.port:
        config["PORT"] = str(parsed.port)

    options = {
        key: value
        for key, value in parse_qsl(parsed.query, keep_blank_values=False)
        if key
    }
    if options:
        config["OPTIONS"] = options
    return config


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)
ENVIRONMENT = os.environ.get(
    "DJANGO_ENVIRONMENT", os.environ.get("ENVIRONMENT", "local")
)
IS_PRODUCTION = ENVIRONMENT.strip().lower() in {"prod", "production"}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        msg = "DJANGO_SECRET_KEY must be set in non-debug environments."
        raise RuntimeError(msg)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "" if IS_PRODUCTION else "localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]
if IS_PRODUCTION and not ALLOWED_HOSTS:
    msg = "DJANGO_ALLOWED_HOSTS must be set when DJANGO_ENVIRONMENT=production."
    raise RuntimeError(msg)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "FARM.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "FARM.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DJANGO_DATABASE_URL") or os.environ.get("DATABASE_URL")
if IS_PRODUCTION and not DATABASE_URL:
    msg = "DJANGO_DATABASE_URL must be set when DJANGO_ENVIRONMENT=production."
    raise RuntimeError(msg)

DATABASES = {
    "default": (
        database_config_from_url(DATABASE_URL)
        if DATABASE_URL
        else {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE_BACKEND = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if IS_PRODUCTION
    else "whitenoise.storage.CompressedStaticFilesStorage"
)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_STORAGE_BACKEND,
    },
}


# Basic production security hardening. These can be tuned via environment.
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if env_bool("DJANGO_SECURE_PROXY_SSL_HEADER_ENABLED", default=IS_PRODUCTION)
    else None
)
SECURE_HSTS_SECONDS = env_int(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=31536000 if IS_PRODUCTION else (3600 if not DEBUG else 0),
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SAMESITE = os.environ.get("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.environ.get("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_HTTPONLY = env_bool(
    "DJANGO_CSRF_COOKIE_HTTPONLY",
    default=IS_PRODUCTION,
)
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)

BASE_URL = os.environ.get("DJANGO_BASE_URL", "")


def validate_production_configuration() -> None:
    """Fail fast on configuration that is unsafe for regulated production."""
    if not IS_PRODUCTION:
        return

    errors: list[str] = []
    parsed_base_url = urlsplit(BASE_URL) if BASE_URL else None
    parsed_database_url = urlparse(DATABASE_URL) if DATABASE_URL else None

    if DEBUG:
        errors.append("DJANGO_DEBUG must be false.")
    if SECRET_KEY.startswith(("dev-", "test-", "ci-")):
        errors.append("DJANGO_SECRET_KEY must not use a development/test prefix.")
    if len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5:
        errors.append("DJANGO_SECRET_KEY must be at least 50 chars and high entropy.")
    if not ALLOWED_HOSTS:
        errors.append("DJANGO_ALLOWED_HOSTS must be set.")
    if "*" in ALLOWED_HOSTS:
        errors.append("DJANGO_ALLOWED_HOSTS must not contain '*'.")
    if not BASE_URL:
        errors.append("DJANGO_BASE_URL must be set.")
    if not SECURE_SSL_REDIRECT:
        errors.append("DJANGO_SECURE_SSL_REDIRECT must be enabled.")
    if not SESSION_COOKIE_SECURE:
        errors.append("DJANGO_SESSION_COOKIE_SECURE must be enabled.")
    if not CSRF_COOKIE_SECURE:
        errors.append("DJANGO_CSRF_COOKIE_SECURE must be enabled.")
    if SECURE_HSTS_PRELOAD and SECURE_HSTS_SECONDS < 31536000:
        errors.append("DJANGO_SECURE_HSTS_SECONDS must be at least 31536000.")
    if parsed_base_url and (
        parsed_base_url.scheme != "https"
        or parsed_base_url.hostname in {"localhost", "127.0.0.1"}
    ):
        errors.append("DJANGO_BASE_URL must be a public HTTPS URL.")
    if parsed_database_url and parsed_database_url.scheme == "sqlite":
        errors.append("DJANGO_DATABASE_URL must use PostgreSQL in production.")

    if errors:
        joined = " ".join(errors)
        msg = f"Unsafe production configuration: {joined}"
        raise RuntimeError(msg)


validate_production_configuration()
