# Generated by Django 5.0 on 2023-12-23 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0017_alter_model_file_model_file_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model_file",
            name="model_file_splitted_file",
        ),
    ]
