# Generated by Django 5.0 on 2023-12-24 01:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0033_alter_local_project_local_project_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="queue_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
