# Generated by Django 5.0 on 2023-12-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fl_client", "0040_alter_model_file_options_queue_queue_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="queue_model_type",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
