# Generated by Django 5.0 on 2023-12-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fl_client",
            "0051_dataset_dataset_type_alter_dataset_dataset_format_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="model_name",
            field=models.CharField(max_length=200),
        ),
    ]
