apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aimer-prod

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - services.yaml
  - deployments.yaml
  - ingress.yaml
  - network-policies.yaml
  - pod-disruption-budgets.yaml
  - hpa.yaml

images:
  - name: docker.io/smartappli/aimer
    newName: docker.io/smartappli/aimer
    digest: sha256:9abb8d94636b430c859d55c39855c3ba68b8617643b9221b874ea56bd79a89b4
  - name: docker.io/smartappli/aimer-rag
    newName: docker.io/smartappli/aimer-rag
    digest: sha256:0a70507ce0e9f85a82257f72b15a153e6d79dbecc94ded19953a11cebe88875e
  - name: docker.io/smartappli/mage-api
    newName: docker.io/smartappli/mage-api
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
  - name: docker.io/smartappli/farm
    newName: docker.io/smartappli/farm
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
