apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aimer-prod

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - services.yaml
  - deployments.yaml
  - ingress.yaml
  - network-policies.yaml
  - pod-disruption-budgets.yaml
  - hpa.yaml

images:
  - name: docker.io/smartappli/aimer
    newName: docker.io/smartappli/aimer
    digest: sha256:388bdc77b644e140450ef30c047c565fbb4f41d4ae7136f1b7ebc0eafca9c256
  - name: docker.io/smartappli/aimer-rag
    newName: docker.io/smartappli/aimer-rag
    digest: sha256:64660f939a41739e78b596320fbe24c3c47397c781c98e9a911b81c29f096307
  - name: docker.io/smartappli/mage-api
    newName: docker.io/smartappli/mage-api
    digest: sha256:9e4f3baa5da8a1013096daca6d246eeca0dd576409896b32dd057fa489c9495c
  - name: docker.io/smartappli/farm
    newName: docker.io/smartappli/farm
    digest: sha256:afae341d0ee85f1daa28736a7a367d2e59f6158ca2adbb4e0dee0635d1482ce7
