apiVersion: v1
kind: ServiceAccount
metadata:
  name: aimer-web
  labels:
    app.kubernetes.io/part-of: aimer
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aimer-rag
  labels:
    app.kubernetes.io/part-of: aimer
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mage
  labels:
    app.kubernetes.io/part-of: aimer
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: farm
  labels:
    app.kubernetes.io/part-of: aimer
automountServiceAccountToken: false

