name: Flake8 Lint

on: [push, pull_request]

concurrency:
  group: flake8-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          update-pip: "true"
          exclude: "migrations,settings.py"
          ignore: "E501,F401,I900,W503,W504"
          max-line-length: "120"
          plugins: "flake8-builtins flake8-commas flake8-errmsg flake8-fixme  pep8-naming flake8-pie flake8-use-pathlib flake8-return flake8-type-checking flake8-todo flake8-tidy-imports flake8-bugbear flake8-django flake8-bandit TorchFix pandas-vet flake8-logging-format flake8-requirements"
