name: Flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          update-pip: "true"
          exclude: "fl_client/migrations/*.py"
          ignore: "E501,F401,W503,W504"
          max-line-length: "125"
          plugins: "flake8-bugbear"
