name: Dependencies License Checker

on:
  push:
    branches:
      - master

  workflow_call:

  pull_request:
    branches:
      - "**"

concurrency:
  group: licensing-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        cache: 'pip'
    - name: Get explicit and transitive dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m uv pip install -r requirements.txt
        python -m uv pip freeze > requirements-all.txt
    - name: Check python
      id: license_check_report
      uses: pilosus/action-pip-license-checker@v3
      with:
        requirements: 'requirements-all.txt'
        fail: 'NetworkCopyleft'
        exclude: '(?i)^(pylint|tbb|nvidia|aio[-_]*).*'
        verbose: 1
        github-token: ${{ secrets.OAUTH_TOKEN_GITHUB }}
    - name: Save report
      if: ${{ always() }}
      run: echo "${{ steps.license_check_report.outputs.report }}" > license-report.json
    - name: Upload artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: license-report
        path: license-report.json

