name: Python license check action

on:
  push:
    branches:
      - master

env:
  DEP_PATH: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Python License Check
        uses: aufdenpunkt/python-license-check-action@main
