name: Nightlies

on:
  schedule:
    - cron: "0 00 * * *" # 12am UTC, 5:30pm Indian, 9pm Brazil, 11am AEDT
  workflow_dispatch:
    inputs:
      none:
        description: "Run Nightlies Tests Manually"
        required: false

jobs:
  call-Licenses-Check:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    uses: Smartappli/AIMER/.github/workflows/liccheck.yml@master

  call-UT-common_training:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    uses: Smartappli/AIMER/.github/workflows/UT_common_training.yml@master

  call-UT-common_models_A:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_a.yml@master

  call-UT-common_models_B:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_A
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_b.yml@master

  call-UT-common_models_C:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_B
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_c.yml@master

  call-UT-common_models_D:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_C
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_d.yml@master

  call-UT-common_models_E:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_D
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_e.yml@master

  call-UT-common_models_F:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_E
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_f.yml@master

  call-UT-common_models_G:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_F
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_g.yml@master

  call-UT-common_models_I:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_G
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_i.yml@master

  call-UT-common_models_L:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_I
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_l.yml@master

  call-UT-common_models_M:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_L
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_m.yml@master

  call-UT-common_models_R:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_M
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_r.yml@master

  call-UT-common_models_S:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_R
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_s.yml@master

  call-UT-common_models_T:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_S
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_t.yml@master

  call-UT-common_models_V:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_T
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_v.yml@master

  call-UT-common_models_W:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_V
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_w.yml@master

  call-UT-common_models_X:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_models_W
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_x.yml@master
