name: Nightlies

on:
  schedule:
    - cron: "0 12 * * *" # 12am UTC, 5:30pm Indian, 9pm Brazil, 11am AEDT
  workflow_dispatch:
    inputs:
      none:
        description: "Run Nightlies Tests Manually"
        required: false

jobs:
  call-UT-common_training:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    uses: Smartappli/AIMER/.github/workflows/UT_common_training.yml@master

  call-UT-common_models_n:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_n.yml@master

  call-UT-common_models_p:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_p.yml@master

  call-UT-common_models_R:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_r.yml@master

  call-UT-common_models_S:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_s.yml@master

  call-UT-common_models_T:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_t.yml@master

  call-UT-common_models_V:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_v.yml@master

  call-UT-common_models_W:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_w.yml@master

  call-UT-common_models_X:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_x.yml@master

  call-Licenses-Check:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: ['call-UT-common_models_N', 'call-UT-common_models_P', 'call-UT-common_models_R', 'call-UT-common_models_S',
            'call-UT-common_models_T', 'call-UT-common_models_V', 'call-UT-common_models_W', 'call-UT-common_models_X']
    uses: Smartappli/AIMER/.github/workflows/liccheck.yml@master
