name: Nightlies Models - PART B

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: nightlies_modesl_B-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  call-UT-common_training:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    uses: Smartappli/AIMER/.github/workflows/UT_common_training.yml@master

  call-UT-common_models_N:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_n.yml@master

  call-UT-common_models_P:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_p.yml@master

  call-UT-common_models_R:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_r.yml@master

  call-UT-common_models_S:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_s.yml@master

  call-UT-common_models_T:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: call-UT-common_training
    uses: Smartappli/AIMER/.github/workflows/UT_common_models_t.yml@master

  call-Licenses-Check:
    if: github.repository == 'Smartappli/AIMER' # don't run on forks
    needs: ['call-UT-common_models_N', 'call-UT-common_models_P', 'call-UT-common_models_R', 'call-UT-common_models_S',
            'call-UT-common_models_T']
    uses: Smartappli/AIMER/.github/workflows/liccheck.yml@master
