name: Pip-audit

on:
  schedule:
    - cron: "0 03 * * *" # 12am UTC, 5:30pm Indian, 9pm Brazil, 11am AEDT
  workflow_dispatch:
    inputs:
      none:
        description: "Run Nightlies Tests Manually"
        required: false

concurrency:
  group: pipaudit-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install
        run: |
          python -m pip install -r requirements.txt

      - uses: pypa/gh-action-pip-audit@v1
        with:
          vulnerability-service: osv
          
