
on:
  push:
    branches:
      - master

  workflow_call:

  pull_request:
    branches:
      - "**"

concurrency:
  group: linting-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install git+https://github.com/pycaret/pycaret.git
        pip install pylint pylint-django
    - name: Analysing the code with pylint
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          # For Windows, use the double quotes around the wildcard to expand correctly
          pylint --load-plugins pylint_django --django-settings-module=lab.settings "**/*.py"
        else
          # For Linux and macOS, use single quotes and find command for recursive globbing
          find . -name '*.py' -exec pylint --load-plugins pylint_django --django-settings-module=lab.settings {} +
        fi
