name: Pylint

on:
  push:
    branches:
      - master

  workflow_call:

  pull_request:
    branches:
      - "**"

concurrency:
  group: linting-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install git+https://github.com/pycaret/pycaret.git
        pip install pylint pylint-django
    - name: Analysing the code with pylint
      run: |
        if [ "$(uname)" == "Darwin" ]; then
          # For macOS, use the find command for recursive globbing
          find . -name "*.py" | xargs pylint --load-plugins pylint_django --django-settings-module=lab.settings
        elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
          # For Linux, use the find command for recursive globbing
          find . -name "*.py" | xargs pylint --load-plugins pylint_django --django-settings-module=lab.settings
        else
          # For Windows, use double quotes around the wildcard to expand correctly
          pylint --load-plugins pylint_django --django-settings-module=lab.settings "**/*.py"
        fi
