name: Release Drafter

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
