name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - uses: chartboost/ruff-action@v1
        with:
          args: 'check --select C90,D,E,F,I,NPY,RUF,UP,W --ignore F401 --fixable ALL --fix'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: 'ruff'
          create_branch: true
          commit_message: 'style fixes by ruff'
