name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: chartboost/ruff-action@v1
        with:
          args: 'check --select C90,E,F,I,NPY,RUF,UP,W --ignore E501,F401 --output-format github --diff --exclude fl_client/migrations,fl_server/migrations'
