name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: chartboost/ruff-action@v1
        with:
          args: 'check --select C90,E,F,I,NPY,RUF,UP,W --ignore C901,E501,F401 --exclude fl_client/migrations,fl_server/migrations'
