name: Secret Leaks

on:
  push:
    branches:
      - master
  
 jobs: 
   trufflehog:
     name: Secret Leaks
     runs-on: ubuntu-latest 
     steps: 
       - name: Checkout code 
         uses: actions/checkout@v4 
         with: 
           fetch-depth: 0 
       - name: Secret Scanning 
         uses: trufflesecurity/trufflehog@main