name: Unit_Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install git+https://github.com/pycaret/pycaret.git
    - name: Fl_client unit tests
      run: |
        python manage.py test fl_client.tests
    - name: Fl_common unit tests
      run: |
        python manage.py test fl_common.tests
    - name: FL_server units tests
      run: |
        python manage.py test fl_server.tests