name: UT_Common_Models_N

on:
  workflow_call:

concurrency:
  group: ut_common_models_n-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test-nasnet-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m uv pip install coverage
        python -m uv pip install -r tests.txt
    - name: Fl_common Models Nasnet
      run: |
        coverage run manage.py test fl_common.tests.tests_models_nasnet
        coverage xml -o coverage-nasnet.xml
        coverage report        

  test-nest-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: test-nasnet-models
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m uv pip install coverage
        python -m uv pip install -r tests.txt
    - name: Fl_common Models Nest
      run: |
        coverage run manage.py test fl_common.tests.tests_models_nest
        coverage xml -o coverage-nest.xml
        coverage report

  test-nextvit-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: test-nest-models
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m uv pip install coverage
        python -m uv pip install -r tests.txt
    - name: Fl_common Models Nextvit
      run: |
        coverage run manage.py test fl_common.tests.tests_models_nextvit
        coverage xml -o coverage-nextvit.xml
        coverage report        

  test-nfnet-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: test-nextvit-models
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m uv pip install coverage
        python -m uv pip install -r tests.txt
    - name: Fl_common Models Nfnet
      run: |
        coverage run manage.py test fl_common.tests.tests_models_nfnet
        coverage xml -o coverage-nfnet.xml
        coverage report        
