name: UT_Common_Models_M

on:
  workflow_call:

concurrency:
  group: ut_common_models_m-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test-m-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m uv pip install -r tests.txt
    - name: Mambaout
      run: |
        python manage.py test fl_common.tests.tests_models_mambaout
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Maxvit
      run: |
        python manage.py test fl_common.tests.tests_models_maxvit
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Metaformer
      run: |
        python manage.py test fl_common.tests.tests_models_metaformer
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Mlpmixer
      run: |
        python manage.py test fl_common.tests.tests_models_mlp_mixer
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Mnasnet
      run: |
        python manage.py test fl_common.tests.tests_models_mnasnet
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Mobilenet
      run: |
        python manage.py test fl_common.tests.tests_models_mobilenet
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Mobilevit
      run: |
        python manage.py test fl_common.tests.tests_models_mobilevit
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Mvitv2
      run: |
        python manage.py test fl_common.tests.tests_models_mvitv2
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/* 
