name: UT_Common_Models_C

on:
  workflow_call:

concurrency:
  group: ut_common_models_c-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test-c-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true    
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m uv pip install -r tests.txt
    - name: Cait
      run: |
        python manage.py test fl_common.tests.tests_models_cait
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Coat
      run: |
        python manage.py test fl_common.tests.tests_models_coat
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Convit
      run: |
        python manage.py test fl_common.tests.tests_models_convit
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Convmixer
      run: |
        python manage.py test fl_common.tests.tests_models_convmixer
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Convnext
      run: |
        python manage.py test fl_common.tests.tests_models_convnext
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Crossvit
      run: |
        python manage.py test fl_common.tests.tests_models_crossvit
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: Cspnet
      run: |
        python manage.py test fl_common.tests.tests_models_cspnet
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/*
    - name: CVT
      run: |
        python manage.py test fl_common.tests.tests_models_cvt
        rm -rf /home/runner/.cache/huggingface/*
        rm -rf /home/runner/.cache/torch/* 
